### ISSUE TITLE
Implement the mentor profile public page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#10]
### Description
As part of this issue, we need to create the "mentor profile" public page, which should closely match the provided mockup. This will provide the users with a way to see more information about a mentor, once selected from the mentors public page.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentor profile public page, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=983-4217&mode=design&t=OFxJkHITzop09S2b-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/0010e067-f611-4c46-8461-1cb98861cab1)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#38013cd1-02be-4ac0-9d74-1841d36a796f) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by RandilaP** [comment]
@anjula-sack can i work on this

**Comment by anjula-sack** [comment]
Any updates on this @RandilaP?

**Comment by RandilaP** [comment]
@anjula-sack I made a draft PR https://github.com/sef-global/scholarx-frontend/pull/83
I need to clarify somethings. I hard coding the whole thing. So should I hard code the success stories and Past mentees part

**Comment by anjula-sack** [comment]
> @anjula-sack I made a draft PR #83 I need to clarify somethings. I hard coding the whole thing. So should I hard code the success stories and Past mentees part

Remove the success stories for now, past mentees are required but you can hard code it. @RandilaP
