### ISSUE TITLE
Displaying Alert Message for Previously Applied Mentors

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/scholarx-frontend#126]
**Describe the bug**
When a user navigates to a mentor profile they have already applied for, the "Apply" button is still visible, leading to confusion and potential duplicate applications.

**To Reproduce**
1. Go to the Home Page.
2. Click on your profile picture.
3. Navigate to the Dashboard.
4. View your list of applied mentors.
5. Click on a mentor profile that you have already applied for.
6. Observe that the "Apply" button is still present.

**Expected behavior**
When a user views a mentor profile they have already applied for, an alert message should be displayed stating "You have already applied for this mentor."

**Screenshots**
![apply button issue](https://github.com/sef-global/scholarx-frontend/assets/48531182/e0d8e286-bfc4-4aee-8651-32b392772e75)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser Firefox
 - Version 127.0.2

**Additional context**
Ensuring this feature is integrated seamlessly with the current user interface is important for a smooth user experience. This will prevent confusion and streamline the application process for users.

**Are you working on it?**
No

**Comment by ThaminduNethmina** [comment]
Can I work on this?

**Comment by mayura-andrew** [comment]
@ThaminduNethmina  Yeah go head 🚀

**Comment by mayura-andrew** [comment]
Hi @ThaminduNethmina any updates on this issue?

**Comment by mayura-andrew** [comment]
@ThaminduNethmina this issue is already implemented.
