### ISSUE TITLE
Contact number is not being validated in Mentee Application Form

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/scholarx-frontend#128]
**Describe the bug**

**To Reproduce**
1. Go to Home Page.
2. Click on 'Find a Mentor'.
3. Click on one of the available mentor profiles.
4. Click on the "Apply" button.
5. On the mentee application page, locate the contact number input field.
6. Enter an invalid contact number (e.g., a number that is too long).
7. Click 'Next.'  

**Expected behavior**

The contact number input field should validate the input using a suitable regex pattern. If an invalid contact number is entered, the system should display a proper error message instructing the mentee to reenter a valid contact number. The mentee should not be able to proceed to the next step until a valid contact number is provided.

**Screenshots**

![contact](https://github.com/sef-global/scholarx-frontend/assets/48531182/3117ab9d-15df-4c9c-901d-9d63975be81a)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser Firefox
 - Version 128.0

**Additional context**

**Are you working on it?**
No

**Comment by Malinhara** [comment]
Also, email is not validated properly,
I fixed it

**Comment by mayura-andrew** [comment]
Hi @Malinhara Yes you're right! Are you working on this?

**Comment by Malinhara** [comment]
I fixed it ,can you check it @mayura-andrew

**Comment by mayura-andrew** [comment]
![image](https://github.com/user-attachments/assets/23754848-2947-413a-a2d7-afb03cdf33f8)
this Graduated Year input also needs to validate @Malinhara

**Comment by mayura-andrew** [comment]
@Malinhara Hi any updates on this issue ?

**Comment by Malinhara** [comment]
No @mayura-andrew

**Comment by mayura-andrew** [comment]
@Malinhara you're working on this issue right?

**Comment by AbishananGaneshalingam** [comment]
me

**Comment by anjula-sack** [comment]
Any updates @eazerabi?

**Comment by Disura-Randunu** [comment]
@anjula-sack @dilankavishka  Shall I work on this?

**Comment by AbishananGaneshalingam** [comment]
@dilankavishka  May you do that brother

**Comment by dilankavishka** [comment]
Alright @eazerabi .
@Disura-Randunu  Go ahead!

**Comment by Disura-Randunu** [comment]
@anjula-sack is the contactNo regex should support only Sri Lankan mobile numbers?

**Comment by Disura-Randunu** [comment]
@anjula-sack 
Made the PR for Modified validations on metee registration schema.
