### ISSUE TITLE
Add loading indicator while fetching mentor profiles

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/scholarx-frontend#130]
**Describe the bug**

When users click on the "Find a Mentor" button on the Home Page, there is no loading indicator displayed while the application is fetching mentor profiles from the backend API. This can lead to a poor user experience, as users may not know if the application is still processing their request or if there is an issue with the API response.

**To Reproduce**
1. Go to Home Page
2. Click on the 'Find a Mentor' button
3. Observe that no loading indicator is displayed while the application is fetching mentor profiles

**Expected behavior**

When the user clicks on the "Find a Mentor" button, a loading spinner or indicator should be displayed to inform the user that the application is processing their request and fetching mentor profiles from the backend API. The loading indicator should be visible until the API response is received and the mentor profiles are displayed on the page.

**Screenshots**

https://github.com/user-attachments/assets/6422fcb1-5f10-4977-845c-c56b7b9741c8

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser Firefox
 - Version 128.0
 
**Additional context**

**Are you working on it?**
No

**Comment by inushaPeiris** [comment]
I will be working on this!

**Comment by mayura-andrew** [comment]
@inushaPeiri go head🚀

**Comment by mayura-andrew** [comment]
@inushaPeiris Hi, any updates on this issue ?

**Comment by mayura-andrew** [comment]
@inushaPeiris this issue is already implemented, sorry. Thank you :)

**Comment by inushaPeiris** [comment]
@mayura-andrew Noted!
