### ISSUE TITLE
Update the mentee FAQ

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend#134]
**Is your feature request related to a problem? Please describe.**
- We need to update the FAQ for mentees

**Describe the solution you'd like**
- Add the following to the FAQ

Q: Is this a free program?

A: Yes, this is a free program.

Q: Who can apply for ScholarX?

A: While anyone can apply for ScholarX, priority will be given to undergraduates.

**Comment by ItsLasa** [comment]
Can I work on this issue?

**Comment by anjula-sack** [comment]
@YoshithaRathnayake Are you working on this?

**Comment by ItsLasa** [comment]
@anjula-sack Can i work ?

**Comment by anjula-sack** [comment]
go ahead @ItsLasa
