### ISSUE TITLE
Implement the mentee profile public view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#14]
### Description
As part of this issue, we need to create the "mentee profile" public view, which should closely match the provided mockup. This will provide the users with a way to see more information about a mentee.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentee profile public view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1643-1553&mode=design&t=OFxJkHITzop09S2b-4

![Image](https://github.com/sef-global/scholarx-frontend/assets/70215958/8e9d8fd8-c5d4-4f3b-9c47-7f1ea6b87d7f)

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by anjula-sack** [comment]
This is implemented
