### ISSUE TITLE
The login form on the path(/mentors/login button) not visible and accessible properly.

### ISSUE THREAD

**Issue by hesh-ftw** [sef-global/scholarx-frontend#142]
**To Reproduce**
1. Go to 'home page '
2. Click on 'mentors'
3. Then Click on 'find a mentor'
4. Click on 'login'
5. See error

![Screenshot 2024-07-24 101744](https://github.com/user-attachments/assets/f2a64482-bbb8-45a6-9847-bced787618bf)

OS: windows 11
Browser: chrome

**Comment by mayura-andrew** [comment]
Hi @hesh-ftw are you working on this issue?

**Comment by anjula-sack** [comment]
Hi @hesh-ftw, Can you try this again seems to be fixed.

**Comment by mayura-andrew** [comment]
@hesh-ftw Thank you for pointing out this issue. 
![image](https://github.com/user-attachments/assets/c621dced-837e-40ba-a5d5-e3055a42ed4f)
