### ISSUE TITLE
Implement the mentee application view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#15]
### Description
As part of this issue, we need to create the mentee applications view, which should closely match the provided mockup. This will provide the mentees with a way to apply for a mentor.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentee profile public view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=2605-4967&mode=design&t=4rAK5DBPmyfRYE3Q-4

![image](https://github.com/sef-global/scholarx-frontend/assets/61134846/07b235ab-01f2-4c69-8949-2053cb1663b6)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#bd578969-f1a3-4b8b-8dc8-d8d4450f5fc0) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by Piumal1999** [comment]
According to the new application structure, the mentee application process will differ from the one depicted in the mockups. Isn't that right, @anjula-sack @Madhawa97 @MethmaPeiris99?

**Comment by Madhawa97** [comment]
Yes. The mokups seems to be outdated. We can discuss this in the stand-up today. @Piumal1999

**Comment by anjula-sack** [comment]
Implemented with https://github.com/sef-global/scholarx-frontend/pull/93
