### ISSUE TITLE
Change the Facebook logo to Meta logo

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend#153]
**Is your feature request related to a problem? Please describe.**
In "Our mentors are from page" replace the facebook logo with meta logo

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/09aa98b2-c45a-45f9-971d-e6d2bfa189d5">

**Describe the solution you'd like**
- Change the Facebook logo to Meta logo

**Comment by ItsLasa** [comment]
@anjula-sack Can i work on this issue?

**Comment by anjula-sack** [comment]
Sure go ahead @ItsLasa
