### ISSUE TITLE
Add option to "Read and Agree" with mentor and mentee guides at the application process

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#163]
**Is your feature request related to a problem? Please describe.**
Currently, there is no formal mechanism to ensure that mentors and mentees have read and agreed to the guidelines and terms before submitting their application, which could lead to misunderstandings or non-compliance during the mentoring program.

**Describe the solution you'd like**
Implement a mandatory "Read and Agree" step for mentors and mentees before they can submit an application.

- [ ] Add checkbox for agreeing to with the guides
- [ ] Add agreement to volunteer during the mentoring program
- [ ] Prevent application submission if terms are not agreed to

**Describe alternatives you've considered**

**Additional context**
Guides are currently linked as an external resource and will be added to the platform with #164

**Comment by RandilaP** [comment]
@anjula-sack

**Comment by anjula-sack** [comment]
Any updates on this @RandilaP?
