### ISSUE TITLE
Implement UI for mentor and mentee guides linked to application process

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#164]
**Is your feature request related to a problem? Please describe.**
Currently, mentors and mentees do not have easy access to detailed guides within the platform, which can lead to confusion or lack of clarity regarding their roles and responsibilities, and there is no system in place to ensure they have acknowledged and agreed to the guidelines before proceeding.

**Describe the solution you'd like**
Create a user interface to display comprehensive guides for mentors and mentees within the platform, with the ability to access and acknowledge these guides during the application process and possibly from the profile menu.

- Design and implement a “Guides” section accessible during the application process and from the profile menu
- Create a modal/ page to display Mentor and Mentee guides
- Ensure the guide content is responsive and readable on all device sizes
- Add a feature for users to acknowledge they have read and agree to the guides during the application process

	
**Describe alternatives you've considered**

**Additional context**
Currently the guides are linked as an external resource.

**Comment by anjula-sack** [comment]
This is implemented
