### ISSUE TITLE
Add country selection dropdown and display flags for mentor profiles

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#165]
**Is your feature request related to a problem? Please describe.**

The current system uses free text input for country, leading to inconsistencies and potential invalid entries. A standardized dropdown will ensure data consistency and enable proper flag display.

**Describe the solution you'd like**

Implement a feature to allow mentors to select their country of residence from a dropdown and display a corresponding flag on their profile.

- [ ] Add a country selection dropdown to the mentor profile edit form
- [ ] Implement a component to display country flags on mentor profiles
- [ ] Update mentor profile view to show the flag alongside other profile information
- [ ] Ensure responsive design and proper sizing of flags for different screen sizes
- [ ] Implement error handling for cases where flag images fail to load

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here

**Suggestions for flag display**
1. Use a third-party API that serves flag images based on country codes (e.g., https://flagcdn.com or https://flagpedia.net)
2. Use Unicode country code flags (emoji) which are supported by most modern browsers
3. Implement a local mapping of country codes to flag image files, stored in the application's static assets

**Comment by Akshaydotcom** [comment]
Hey! Can I work on this? @anjula-sack

**Comment by anjula-sack** [comment]
Go ahead. @Akshaydotcom You can get the countries using `/countries` endpoint
