### ISSUE TITLE
Implement monthly check-In form

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#167]
**Is your feature request related to a problem? Please describe.**
Currently, there is no dedicated interface for users to submit their monthly check-ins, which can lead to inconsistent data collection.

**Describe the solution you'd like**
Create a user interface for submitting monthly check-ins.

- [ ] Design and implement a form for monthly check-ins
- [ ] Implement client-side validation for the check-in form
- [ ] Ensure the form is responsive and accessible

**Describe alternatives you've considered**

**Additional context**
Related backend issue: [https://github.com/sef-global/scholarx-backend/issues/157](https://github.com/sef-global/scholarx-backend/issues/157)

**Comment by anjula-sack** [comment]
https://forms.gle/eXchAtQPvh5xad3P7
