### ISSUE TITLE
Update mentor profile UI

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#171]
**Is your feature request related to a problem? Please describe.**
The mentor profile page should highlight the number of total applications, available slots in a more user friendly way.

**Describe the solution you'd like**
Update mentor profile to closely resemble the following design:

![image](https://github.com/user-attachments/assets/eaf2c49a-01e8-43b5-9408-0e8b77ba2024)

**Describe alternatives you've considered**

**Additional context**

**Comment by AnsarMahir** [comment]
As requested
