### ISSUE TITLE
Navigation bar splitting into two rows on medium screen sizes

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#175]
### Describe the bug
The navigation bar splits into two rows when viewed on an iPad Air screen size, causing a layout issue. This behavior is observed on some mid-size devices, including the iPad Air.

### To reproduce
1. Go to the application on an iPad Air or simulate an iPad Air screen size using developer tools.
2. Observe the navigation bar.
3. See that the navigation bar is split into two rows.

### Expected behavior
The navigation bar should remain on a single row regardless of the screen size and should appear similar to the mobile view on devices that cannot accommodate all navigation links.

### Screenshots
![Screenshot 2024-08-25 at 21 17 51](https://github.com/user-attachments/assets/bf3c928d-9b73-4752-96bd-c4e89f7547e3)

### Are you working on it?
No

**Comment by ItsLasa** [comment]
@Madhawa97  Can i work on this issue?

**Comment by Madhawa97** [comment]
Sure go ahead @ItsLasa
