### ISSUE TITLE
Extra margin added to content in mobile view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#176]
### Describe the bug
Extra margin is being added to the content when viewed on mobile devices, leading to unnecessary white space and affecting the overall layout.

### To reproduce
1. Go to the application on a mobile device or simulate a mobile screen size using developer tools.
2. Scroll through the content.
3. See that there is extra margin added to the content, causing misalignment.

### Expected behavior
The content should not have any extra margin in mobile view, ensuring proper alignment and spacing.

### Screenshots
<p align="center">
  <img src="https://github.com/user-attachments/assets/4ca70e04-6442-4012-ae3e-0f15da5ed0dc" alt="Screenshot 2024-08-25 at 21 16 56" width="45%" />
  <img src="https://github.com/user-attachments/assets/0803f26d-32ca-4ff6-89c6-ae9fe981bab7" alt="Screenshot 2024-08-25 at 21 26 44" width="45%" />
</p>

### Are you working on it?
No

**Comment by Akshaydotcom** [comment]
Hey! Can I work on this? @Madhawa97

**Comment by Madhawa97** [comment]
@Akshaydotcom sure go ahead please.

**Comment by Akshaydotcom** [comment]
Hey @Madhawa97, In the latest version, I believe the Frontend APIs need pagination related constraints to work. 
Could you please let me know if this is an issue, would love to connect?

**Comment by anjula-sack** [comment]
@Akshaydotcom The pagination issue is fixed now. Let me know if you are available to work on this.
