### ISSUE TITLE
Breadcrumb names split into two lines on mobile view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#177]
**Describe the bug**
In the mobile view of the ScholarX application, on the mentee public profile page, long names in the breadcrumb navigation are splitting into two lines, causing a formatting issue and potentially affecting readability.

**To Reproduce**
1. Open the ScholarX application on a mobile device
2. Click on Find a mentor from the nav bar
3. Select a mentor with some mentees in progress.
4. Click on a mentee to navigate to a mentee profile page with long names in the breadcrumb (e.g., Stephany Ernser > Grace Wiegand)
5. Observe that the names in the breadcrumb split into two lines

**Expected behavior**
The breadcrumb should display all names on a single line, potentially with a truncation or alternative solution to handle long names without line breaks.

**Screenshots**
<img width="359" alt="image" src="https://github.com/user-attachments/assets/3a596ab1-6e84-46e3-9833-289e9e114d1f">

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS  - Browser: Not specified 
 - Version: Not specified

**Additional context**

**Are you working on it?**
No

**Comment by Sanjana0823** [comment]
Can I work on this ?

**Comment by Madhawa97** [comment]
Sure!
