### ISSUE TITLE
Fix profile image loading in admin dashboard

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#178]
**Describe the bug**
In the admin dashboard, profile images for both mentees and mentors are not loading properly when viewing their applications or profiles. This occurs specifically when the user's image is not available or accessible.

**To Reproduce**
1. Login as an admin
2. Go to the admin dashboard
3. Navigate to "Manage Mentee Applications" section
4. Select a mentee to view their profile
5. Observe that the mentee's profile image is not loading (happens only if the image is a empty string or inaccessible)
Alt:
6. Go back and navigate to "Manage Mentor Applications" section
7. Select a mentor to view their profile
8. Observe that the mentor's profile image is not loading

**Expected behavior**
Profile images should load correctly for both mentees and mentors in their respective application views. If an image is not available, a placeholder or default image should be displayed.

**Screenshots**
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/f3750733-ff2b-4c4e-ac67-9ca7524779a5">

**Expected behaviour**
![image](https://github.com/user-attachments/assets/af3677aa-ea10-4009-ad15-c6f63d6844c5)

**Desktop (please complete the following information):**
 - OS: Not specified
 - Browser: Not specified
 - Version: Not specified

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
- The issue occurs in both the mentee and mentor application views in the admin dashboard.
- The problem is specifically related to cases where the user's image is not available or accessible.
- There is an existing React component called `ProfilePic` in the codebase that should be used to replace the current `img` tag implementation.
- ProfilePIc component has already utilised in public mentor and mentee profile pages.

**Are you working on it?**
No

**Comment by dilankavishka** [comment]
I'm Working with this issue. @anjula-sack

**Comment by anjula-sack** [comment]
Any updates on this @dilankavishka?

**Comment by dilankavishka** [comment]
Sorry for the Delay! I'll make the PR Today.
