### ISSUE TITLE
Implement mentee dashboard - my mentors view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#18]
### Description
As part of this issue, we need to create the mentee dashboard - my mentors view, which should closely match the provided mockup. This will provide the mentees with a way to see all the mentors they've applied for or working with.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentee dashboard - my mentors view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.
 
**Use the mentor card**

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-2225&mode=design&t=4rAK5DBPmyfRYE3Q-4

<img width="611" alt="image" src="https://github.com/sef-global/scholarx-frontend/assets/43912578/24730e1f-7b6c-4c74-8f5e-06d133c7342b">

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#a044a6e5-1726-4e94-881b-35b773937181) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by mayura-andrew** [comment]
I'll start work on this issue, @anjula-sack
