### ISSUE TITLE
Remove mentor name from the mentee application

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend#191]
**Is your feature request related to a problem? Please describe.**
- When you go to apply for a mentor, at the third step we are showing the mentor's name. We don't really need that remove it.

**Describe the solution you'd like**
- Remove mentor name from the mentee application
-  You can find the relevant page here: https://github.com/sef-global/scholarx-frontend/blob/main/src/pages/MenteeRegistration/index.tsx

**Additional context**
- You need to remove the below part
<img width="1613" alt="Screenshot 2024-09-29 at 9 37 14 AM" src="https://github.com/user-attachments/assets/6b56fc26-a502-4c65-93d4-6978ea635b57">

**Comment by Sanjana0823** [comment]
Can I work on this ?

**Comment by PartishtaP** [comment]
Hey @anjula-sack 
I would like to work on this issue.

**Comment by PartishtaP** [comment]
Please assign me this

**Comment by anjula-sack** [comment]
This is completed @PartishtaP
