### ISSUE TITLE
Mentors and mentees should be redirected to there dashboards after login.

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend#192]
**Is your feature request related to a problem? Please describe.**
- There's no point of showing the homepage for them. Just redirect them their relevant dashboards.

**Describe the solution you'd like**
- Mentors and mentees should be redirected to there dashboards after login.

**Comment by Priyanshu-2005** [comment]
Hey @anjula-sack  I would like to work on this issue kindly assign it to me.

**Comment by Madhawa97** [comment]
Hi @dilankavishka , Are you currently working on this?

**Comment by dilankavishka** [comment]
@Madhawa97 yeah i'm on this. please give me this week for complete this issue.

**Comment by dilankavishka** [comment]
@Disura-Randunu can you do this for me please?
