### ISSUE TITLE
Implement mentor dashboard - my mentees view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#20]
### Description
As part of this issue, we need to create the mentor dashboard - my mentees view, which should closely match the provided mockup. This will provide the mentors with a way to view their mentees. Also this view includes the functionality of setting the mentor availability status. 

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentor dashboard - my mentees view,, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-2309&mode=design&t=4rAK5DBPmyfRYE3Q-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/c76a3aa0-8fc4-45a1-8bf0-df5f7a15f7d8)
![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/d3e748f3-3620-4a0c-8f01-89381a5c3169)

Note: You may want to mock the API refer to the [API doc - Get my mentees](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#a724f37b-6a38-4a47-a0a4-f9b97bf47f67) and [API doc - Update mentor availabiliy](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#3eeb0372-4e07-4a2a-b72d-114d8639783d) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by Gravewalker666** [comment]
@anjula-sack I think it'll be much easier to work on if we divide up this issue even further. As I see it there are few components here that we can make separately and assembled on a view page. 

Components 
- Mentee table 
- Tab switcher button row (for lack of a better term, I'm talking about those My mentee/Application and All/Approved/Rejected button rows)
- Switch (If that's not already included in ant design)

View 
- My mentee view (Which is this issue, that we can get into after we've made those three components that should be in the view)

It'll be a much organised approach if we made them into different issues and worked on them separately. (And I can send more PRs to get more green dots :D)

**Comment by Gravewalker666** [comment]
Tab switcher button row and switch is available on antd, my bad 😄

**Comment by anjula-sack** [comment]
Hi @Gravewalker666, Here's the updated wireframe. Will you be working on this or should I assign someone else?



![Image](https://github.com/sef-global/scholarx-frontend/assets/43912578/d6693de5-e0f3-4395-88bf-be4fe556512f)

**Comment by Gravewalker666** [comment]
Yo @anjula-sack can you assign this to somebody else please? I don't think I'd be able to contribute at this point. Thanks.

**Comment by udeesha-kularathne** [comment]
@anjula-sack Can you please assign this task to me? I'll work on it.

**Comment by udeesha-kularathne** [comment]
![Image](https://github.com/sef-global/scholarx-frontend/assets/45477393/39153d19-96e6-49b0-967a-bb415899cd6c)

Current progress of the MyMentee view

**Comment by anjula-sack** [comment]
@udeesha-kularathne Any updates on this?
