### ISSUE TITLE
Website link appears on Mentor Profile even when not provided

### ISSUE THREAD

**Issue by dilankavishka** [sef-global/scholarx-frontend#200]
**Describe the bug**
When a mentor adds only a LinkedIn URL and not a website URL, both fields (LinkedIn and website) still appear on the mentor profile. The expected behavior is that the website link should only be visible if the mentor has provided a valid website URL.

**To Reproduce**
1. Go to Find a mentor page
2. Click on a Mentor.
3. Click on the **Website** link.
4. If a mentor provides a website link, clicking on the link redirects to the specified website.
5. If no website link is provided, the link incorrectly redirects back to the same page.

**Expected behavior**
The website link should not appear on the mentor profile if the mentor has not provided a valid website URL. Only the LinkedIn URL should be displayed in this case.

**Screenshots**
![Screenshot (42)](https://github.com/user-attachments/assets/090f6a5d-fc76-42dc-9705-2bef19c6f605)

**Additional context**
Ensure a cleaner and more accurate user interface.

**Are you working on it?**
Yes/No

**Comment by yashathwani** [comment]
@dilankavishka  @anjula-sack  Would like to work on this issue . Please assign this to me !!

**Comment by HarshitPachori** [comment]
I would like to work on this issue . Could you explain me like if mentor provides invalid url for linkedin or website , do we have to show these links on website or have to show only if both the  urls are valid ?

**Comment by Priyanshu-2005** [comment]
Hey @dilankavishka I would like to work on this issue kindly assign this issue to me.

**Comment by dilankavishka** [comment]
@yashathwani Sure! Go ahead.

**Comment by YashmithaDilshan27** [comment]
@dilankavishka  Is that issue still open, or has it been resolved?

**Comment by dilankavishka** [comment]
@YashmithaDilshan27 Go ahead!

**Comment by rdwaynedehoedt** [comment]
@anjula-sack  Would like to work on this issue . Please assign this to me !!
