### ISSUE TITLE
Fix the ScholarX logo in the mobile view

### ISSUE THREAD

**Issue by YoshithaRathnayake** [sef-global/scholarx-frontend#205]
**Describe the bug**
Currently, the scholarx logo's width in the navbar is decreased in the resolution (Width = 1023)

**To Reproduce**
1. Go to 'https://scholarx.sefglobal.org'
2. See the error in the mobile view
3. See error

**Expected behavior**
Increase the width of the logo or reduce the height of the logo

**Screenshots**
![image](https://github.com/user-attachments/assets/4aa0fd27-512b-4583-bdb8-fdce8ea31b15)

**Are you working on it?**
No

**Comment by Kinshu-Learner** [comment]
Hi! I would like to work on this issue.
