### ISSUE TITLE
Implement the mentor dashboard - mentee profile view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#21]
### Description
As part of this issue, we need to create the mentor dashboard - mentee profile view, which should closely match the provided mockup. This will provide the mentors with a way to view the profile of a mentee and complete/ terminate the ongoing mentee program. 

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentor dashboard - mentee profile view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-2091&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/ccc0bd35-b9af-4465-a9dd-02711532cfc1)

Note: You may want to mock the API refer to the [API doc - Complete/Terminate ongoing mentee program](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#b5c03158-8704-401d-af6d-49e4402272f0) and [API doc - Get my mentees](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#a724f37b-6a38-4a47-a0a4-f9b97bf47f67) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by Madhawa97** [comment]
@anjula-sack I'm unable to find the endpoint related to getting data of a mentee for this scenario.

**Comment by anjula-sack** [comment]
> @anjula-sack I'm unable to find the endpoint related to getting data of a mentee for this scenario.

This is the API: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#a724f37b-6a38-4a47-a0a4-f9b97bf47f67

`${baseUrl}/api/me/mentees/${menteeId}`

**Comment by Madhawa97** [comment]
Thanks @anjula-sack.

**Comment by anjula-sack** [comment]
This is already implemented
