### ISSUE TITLE
Bug Report: Incorrect Error Message for Month Field in Monthly Check-In Submission Form

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/scholarx-frontend#216]
**Describe the bug**

In the new Monthly Check-In submission form, the first input field is labeled "Month." However, when the user attempts to submit an empty form, the field displays the error message "Title is required." This message should instead display "Month is required."
 
**To Reproduce**
1. Go to the Mentee Dashboard
2. Click on the "Submit Your Monthly Check-In" button.
3. Scroll to the bottom and click Submit without entering any data.
4. Observe the error message.

**Expected behavior**
The error message "Title is required" should instead display "Month is required."

**Screenshots**
![image](https://github.com/user-attachments/assets/e51f1d9a-6365-4047-83d4-4e4770395d60)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser: Chromium 
 - Version: 129.0.6668.100

**Smartphone (please complete the following information):**

**Additional context**

**Are you working on it?**
No

**Comment by KavinduGama** [comment]
I'll work on this
