### ISSUE TITLE
Implement the mentor dashboard - manage mentee applications view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#22]
### Description
As part of this issue, we need to create the mentor dashboard - manage mentee applications view, which should closely match the provided mockup. This will provide the mentors with a way to view all the mentee applications they have.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentor dashboard - manage mentee applications view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-3084&mode=design&t=zBGgiYyW1foSirHq-4

![Image](https://github.com/sef-global/scholarx-frontend/assets/43912578/bec5ce92-e96f-44fb-ba46-ff4ed92ca1c7)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#673bfc7d-2df2-4d1d-9bf8-43c365c3805e) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by udeesha-kularathne** [comment]
@anjula-sack  Can you please assign this task to me? I'll work on it.

**Comment by anjula-sack** [comment]
> @anjula-sack  Can you please assign this task to me? I'll work on it.

Go ahead @udeesha-kularathne
