### ISSUE TITLE
Implement the mentor dashboard - mentee application view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#23]
### Description
As part of this issue, we need to create the mentor dashboard - mentee application view, which should closely match the provided mockup. This will provide the mentors with a way to view an application of a mentee and will also provide the functionality to approve or reject the application.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentor dashboard - mentee application view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-1784&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/f8a46bfe-50e7-4c08-9f7f-7c0337b1851c)

Note: You may want to mock the API refer to the [API doc -
Get specific mentee application/details](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#77165e2b-bffd-4e21-82b8-0b0d5f077c4b) and [API doc - Approve/Reject mentee applications](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#5012cbf9-7821-4513-81b3-7fe774fc47f6) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by anjula-sack** [comment]
This is no longer needed
