### ISSUE TITLE
Implement the admin dashboard - navigation menu

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#25]
### Description
As part of this issue, we need to create the admin dashboard - navigation menu, which should closely match the provided mockup. This will provide the admins with a way to switch between different views available for them.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the admin dashboard - navigation menu, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-2421&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/c2f34129-f925-4929-8f9f-30d6824b1594)

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by Shrenik0321** [comment]
can i work on this?
