### ISSUE TITLE
Implement the admin dashboard - manage mentors view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#28]
### Description
As part of this issue, we need to create the admin dashboard - manage mentors view, which should closely match the provided mockup. This will provide the admins with a way to manage all the mentors with the functionalities for searching, filtering or changing availability.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the admin dashboard - manage mentors view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-3853&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/0bf34482-dbc3-4969-9f94-47db62b88083)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#e48b80ba-df2c-4ffc-b399-edb5f2811618) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by anjula-sack** [comment]
This is implemented with https://github.com/sef-global/scholarx-frontend/pull/90
