### ISSUE TITLE
Implement the admin dashboard - mentor profile view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#29]
### Description
As part of this issue, we need to create the admin dashboard - mentor profile view, which should closely match the provided mockup. This will provide the admins with a way to view the details of a mentor.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the admin dashboard - mentor profile view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-1966&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/70c64da7-dd62-441a-a1a5-4da01b2ec1f9)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#ec8d5137-ea84-43db-8c60-e0c2c3039d2a) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by anjula-sack** [comment]
This is completed with https://github.com/sef-global/scholarx-frontend/pull/94
