### ISSUE TITLE
Create the homepage

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend#3]
### Description
As part of this issue, we need to create the homepage of the project, which should closely match the provided mockup. The project is built using React and Storyboard. The homepage will serve as the main entry point for users, providing them with an overview of the application's features and content.

### Tasks

1. Set up the basic React components and file structure for the homepage.
2. Implement the layout and design of the homepage, following the provided mockup.
3. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
4. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=523%3A6&mode=design&t=MusZHQ3y31nKxoli-1

![Image](https://github.com/sef-global/scholarx-frontend/assets/43912578/11e62a7e-b811-46a6-89fe-3bd651bf67b0)

### Acceptance Criteria

- The homepage closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The homepage is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written

**Comment by MethmaPeiris99** [comment]
Please assign me for this task
