### ISSUE TITLE
Implement the admin dashboard - mentee application view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#31]
### Description
As part of this issue, we need to create the admin dashboard - mentee application view, which should closely match the provided mockup. This will provide the admins with a way to view an application of a mentee and approve/ reject the mentee.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the admin dashboard - mentee application view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-1822&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/8c607422-aa3b-46ab-911f-80363760544e)

Note: You may want to mock the API refer to the [API doc - Get a specific mentees' details](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#30f52753-ba46-4628-b23d-979f0fa45de0) and [API doc - Approve/ Reject a mentee](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#b8139d1e-dd74-45b2-aa1f-3cebfada165e) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by anjula-sack** [comment]
@Piumal1999 Let's use this https://github.com/sef-global/scholarx-frontend/blob/main/src/components/MenteeProfile/index.tsx with additional data like mentor
