### ISSUE TITLE
Implement the admin dashboard - scheduled email view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#33]
### Description
As part of this issue, we need to create the admin dashboard -scheduled email view, which should closely match the provided mockup. This will provide the admins with a way to view all the scheduled emails.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the admin dashboard - scheduled email view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-4001&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/a810b9c3-c3db-4abe-988f-f336ecb0a353)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#ccbab660-6313-428f-9063-c12d27b4606b) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by Madhawa97** [comment]
@anjula-sack I was unable to find the endpoint for this.

**Comment by Madhawa97** [comment]
Just added the endpoint.

**Comment by anjula-sack** [comment]
We won't be doing this.
