### ISSUE TITLE
Implement the admin dashboard - sent email view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#34]
### Description
As part of this issue, we need to create the admin dashboard - sent email view, which should closely match the provided mockup. This will provide the admins with a way to view all the sent emails.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the admin dashboard - sent email view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-4052&mode=design&t=zYi191UOlImykhe8-4

![image](https://github.com/sef-global/scholarx-frontend/assets/61134846/d666f1e8-6727-406a-810e-56e2befe0c67)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#ccbab660-6313-428f-9063-c12d27b4606b) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by Madhawa97** [comment]
@anjula-sack. Get emails endpoint wasn't found in API doc.

**Comment by anjula-sack** [comment]
> @anjula-sack. Get emails endpoint wasn't found in API doc.

Here's the endpoint https://documenter.getpostman.com/view/27421496/2s93m1a4ac#ccbab660-6313-428f-9063-c12d27b4606b

You can use the status query parameter to filter them based on the status.  ex: scheduled @Madhawa97

**Comment by Madhawa97** [comment]
Thank you! @anjula-sack
