### ISSUE TITLE
Implement the admin dashboard - edit email view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#35]
### Description
As part of this issue, we need to create the admin dashboard - edit email view, which should closely match the provided mockup. This will provide the admins with a way to edit emails.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the admin dashboard - edit email view, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-4103&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/5346557a-7f6d-4ccb-a58a-76c5b8ca93df)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#b67fe9f0-6d6f-4484-8254-18fbdfb3e823) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by Madhawa97** [comment]
@anjula-sack. Email send/ schedule endpoint wasn't found in API doc. Plus where do the "drafts" go. and how we create new templates.

**Comment by anjula-sack** [comment]
> @anjula-sack. Email send/ schedule endpoint wasn't found in API doc. Plus where do the "drafts" go. and how we create new templates.

Thanks for noticing, I'll update the doc. You can create the issues using the Kanban board by default they will be draft. @Madhawa97

**Comment by anjula-sack** [comment]
I updated the doc @Madhawa97 can you check?

**Comment by Madhawa97** [comment]
Thanks @anjula-sack. Got it.

**Comment by YashmithaDilshan27** [comment]
I’d love to work on this issue

**Comment by anjula-sack** [comment]
We won't be doing this.
