### ISSUE TITLE
Implement the admin dashboard - platform settings - update mentor application view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#39]
### Description
As part of this issue, we need to create the admin dashboard - platform settings - update mentor application view which should closely match the provided mockup. This will provide the admins with a way to update the mentor application questions.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the update mentor application view following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=1974-3419&mode=design&t=zBGgiYyW1foSirHq-4

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/a415d4c3-f612-400a-8e77-f993f9e2fb7b)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#5dfc48a0-1d49-42c3-bd54-5518d0e7b968) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written.

**Comment by vidura-16** [comment]
Shall I work on this ?

**Comment by dilancn** [comment]
Hi.. Can I work on this issue please? @anjula-sack  @Madhawa97

**Comment by anjula-sack** [comment]
> Hi.. Can I work on this issue please? @anjula-sack @Madhawa97

yeah sure
