### ISSUE TITLE
Implement the user login view

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend#5]
### Description
As part of this issue, we need to create the user login view, which should closely match the provided mockup. The user login will provide the users with a way to log in to the application.

### Tasks

1. Set up the basic React components as required.
2. Implement the layout and design of the homepage, following the provided mockup.
3. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
4. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=2469-4702&mode=design&t=OFxJkHITzop09S2b-4

![image](https://github.com/sef-global/scholarx-frontend/assets/61134846/3e3453cc-e14f-41a7-b713-64278f0e293e)

Note: You may want to mock the API refer to the [API doc](https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=2469-4702&mode=design&t=OFxJkHITzop09S2b-4) to see the relevant details. 

### Acceptance Criteria

- The login view closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The login view is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written

**Comment by RandilaP** [comment]
Can I work on this
