### ISSUE TITLE
Migrate from ant design to tailwind css

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend#50]
**Is your feature request related to a problem? Please describe.**
- Since we decided to use tailwind CSS we need to change the existing components from ant design to tailwind css

**Describe the solution you'd like**
- Create the existing components in tailwind css
- Remove ant design from the project

**Comment by RandilaP** [comment]
Can I work on this @anjula-sack

**Comment by anjula-sack** [comment]
Any updates? @RandilaP

**Comment by vishwaikon** [comment]
Hi @anjula-sack , can I please work on this task? Regards!

**Comment by RandilaP** [comment]
@anjula-sack I'm working on it. I'll send a PR

**Comment by anjula-sack** [comment]
@udeesha-kularathne Use this issue

**Comment by udeesha-kularathne** [comment]
@anjula-sack Okay
