### ISSUE TITLE
Documentation Bug: Incorrect Start Command in README.md

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/scholarx-frontend#62]
**Describe the bug**
The README.md instructs users to run the Node.js frontend application locally using `npm start` after executing `npm install`. However, this leads to errors as the `package.json` file specifies "dev" under the script section instead of "start".

**Screenshots**
![Screenshot_20240103_212050](https://github.com/sef-global/scholarx-frontend/assets/48531182/acd627e8-f591-4d65-aaa8-9afae99e8d67)

**Steps to Reproduce:**
1. Clone the repository.
2. Navigate to the frontend directory.
3. Execute `npm install`.
4. Attempt to start the application using `npm run dev`.

**Expected Behavior:**
The application should start successfully without errors, as indicated in the README.md.

**Actual Behavior:**
Running `npm start` results in errors due to the "dev" script being specified in the package.json file.

**Proposed Solution:**
Update the README.md instructions to reflect the correct command for starting the application, which is `npm run dev` instead of `npm start`.

**Are you working on it?**
Yes

**Comment by anjula-sack** [comment]
Go ahead @mayura-andrew
