### ISSUE TITLE
Implement the edit profile view

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#7]
### Description
As part of this issue, we need to create the edit profile page view, which should closely match the provided mockup. The edit profile view will provide the users with a way to edit the information in their profile.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the edit profile page, following the provided mockup.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=523%3A6&mode=design&t=MusZHQ3y31nKxoli-1

![image](https://github.com/sef-global/scholarx-frontend/assets/70215958/6ee18c16-9257-4b4b-b93d-70aae98e0c1c)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#e52c240e-fb08-4e87-98b6-69ca43f74b0e) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written

**Comment by Madhawa97** [comment]
This page hasn't been implemented yet. Right? Shall we reopen this/ create a new one? @anjula-sack

**Comment by anjula-sack** [comment]
> This page hasn't been implemented yet. Right? Shall we reopen this/ create a new one? @anjula-sack

yeah the components are created but not the page
