### ISSUE TITLE
Implement the mentors public page

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-frontend#9]
### Description
As part of this issue, we need to create the "mentors" public page, which should closely match the provided mockup. This will provide the users with a way to see all the mentors registered on the platform.

### Tasks
1. Set up the basic React components as required.
1. Implement the layout and design of the mentors public page, following the provided mockup.
1. Make sure that both the List view and the Card view is availble and the user can easily switch between them.
1. Integrate the necessary components and assets to achieve the desired functionality and visual appearance.
1. Ensure responsiveness and compatibility across different devices and screen sizes.

### Card View
Mockup: https://www.figma.com/file/nehm2ff8aR7NkPerg39fK9/ScholarX-V2-%7C-Wireframes?type=design&node-id=2504-4902&mode=design&t=OFxJkHITzop09S2b-4

![image](https://github.com/sef-global/scholarx-frontend/assets/61134846/29a79dba-7381-4b8c-9404-c7d05bbb0d17)

Note: You may want to mock the API refer to the [API doc](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#1127356a-3542-4ceb-9477-9d68cf863d5a) to see the relevant details.

### Acceptance Criteria
- The user interface closely resembles the provided mockup.
- All required sections, elements, and content are present and displayed correctly.
- The interface is responsive and works well on various devices and screen sizes.
- The implementation follows best practices and coding standards.
- Unit tests are written

**Comment by anjula-sack** [comment]
@janithlahirukariyawasam Any updates on this?
